package MotorPH;

import com.opencsv.exceptions.CsvValidationException;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.PrintStream;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;

public class ViewSalary extends javax.swing.JFrame {

    public ViewSalary() {
        initComponents();
        showDate();
        this.setLocationRelativeTo(null);
    }

    private void showDate() {
        SimpleDateFormat s = new SimpleDateFormat("yyyy-MM-dd");
        Date d = new Date();
        date.setText(s.format(d));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        label4 = new java.awt.Label();
        date = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        employeeNo = new javax.swing.JTextField();
        hw = new javax.swing.JTextField();
        viewButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        viewEmpData = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        showData = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("View Salary");
        setBackground(new java.awt.Color(204, 204, 204));
        setMinimumSize(new java.awt.Dimension(700, 540));

        jPanel1.setBackground(new java.awt.Color(0, 102, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(150, 100));

        label4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label4.setText("View Salary");

        date.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        date.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(date)
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(date, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        label1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label1.setText("Employee No.:");

        label2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label2.setText("Month :");

        label3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label3.setText("Enter Employee Data To View Salary");

        viewButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        viewButton.setText("View Salary");
        viewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewButtonActionPerformed(evt);
            }
        });

        backButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        backButton.setText("< Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        viewEmpData.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        viewEmpData.setText("View Employee Details");
        viewEmpData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewEmpDataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backButton))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(viewEmpData)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(employeeNo)
                                    .addComponent(hw, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(viewButton)
                .addGap(92, 92, 92))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(employeeNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(viewButton)
                .addGap(18, 18, 18)
                .addComponent(viewEmpData)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 158, Short.MAX_VALUE)
                .addComponent(backButton)
                .addContainerGap())
        );

        label2.getAccessibleContext().setAccessibleName("Month (Ex. July):");
        hw.getAccessibleContext().setAccessibleName("");
        hw.getAccessibleContext().setAccessibleDescription("");

        showData.setEditable(false);
        showData.setColumns(20);
        showData.setRows(5);
        showData.setWrapStyleWord(true);
        showData.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane2.setViewportView(showData);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewButtonActionPerformed
        double baseSalary;
        double allowances;
        try {
            // Get the values entered by the user for employee number and month
            String empNo = employeeNo.getText();
            String month = hw.getText();

            // Initialize instances of 'Attendance' and 'Data' classes
            Attendance attend = new Attendance();
            Data data = new Data();
            StringBuilder salaryInfoText = new StringBuilder();
            
            // Set the employee number and month in the 'Attendance' object
            attend.SetEmployeeNo(empNo);
            attend.SetMonth(month);

            // Set the employee number in the 'Data' object
            data.SetEmployeeNo(empNo);

            // Compute the hours worked for the given employee and month
            attend.ComputeHourWorked();

            // Read employee Data to display
            data.ReadEmployee(empNo);

            allowances = data.RiceAllowance() + data.PhoneAllowance() + data.ClothAllowance();
            baseSalary = (data.HourlyRate() * attend.FinalHW()) + allowances;

            Deduct govt = new Deduct(baseSalary);
            // System out print conversion to display text from jTextArea
            ByteArrayOutputStream output = new ByteArrayOutputStream();
            PrintStream ps = new PrintStream(output);
            PrintStream old = System.out;
            System.setOut(ps);
            govt.Contributions();
            System.out.flush();
            System.setOut(old);
            String deductOutput = output.toString();

            DecimalFormat df = new DecimalFormat("#,##0.00");

            if (data.EmployeeFN() == null) {
                salaryInfoText.append("\n\t*** Employee Not Found! ***").append("\n");
            } else if (attend.FinalHW() != 0) {

                // Construct the salary information
                salaryInfoText.append("Employee No.: ").append(data.EmployeeNo()).append("\n");
                salaryInfoText.append("Employee Name: ").append(data.EmployeeFN()).append(" ").append(data.EmployeeLN()).append("\n");
                salaryInfoText.append("Month: ").append(attend.Month()).append("\n");
                salaryInfoText.append("Hours Worked: ").append(attend.FinalHW()).append("\n");
                salaryInfoText.append("Hourly Rare: ").append(data.HourlyRate()).append(" ").append("PHP").append("\n");
                salaryInfoText.append("\n------------------ Allowances ------------------").append("\n");
                salaryInfoText.append("Rice Subsidy: ").append(data.RiceAllowance()).append("\n");
                salaryInfoText.append("Phone: ").append(data.PhoneAllowance()).append("\n");
                salaryInfoText.append("Cloth: ").append(data.ClothAllowance()).append("\n");
                salaryInfoText.append("Gross Salary: ").append(df.format(baseSalary)).append("\n");
                salaryInfoText.append(" ").append(deductOutput);
                // Add other salary-related information as needed

            } else {
                salaryInfoText.append("\n\t*** No Record For This Month! ***").append("\n");
            }

            // Set the constructed salary information in the text panel
            showData.setText(salaryInfoText.toString());
        } catch (CsvValidationException | IOException | ParseException ex) {
            ex.printStackTrace(); // Handle exceptions properly in your application
        }

    }//GEN-LAST:event_viewButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        HomePage home = new HomePage();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    private void viewEmpDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewEmpDataActionPerformed
        try {
            // Get the value entered by the user for employee number
            String empNo = employeeNo.getText();

            // Initialize instance of 'Data' class
            Data data = new Data();
            StringBuilder infoText = new StringBuilder();

            // Set the employee number in the 'Data' object
            data.SetEmployeeNo(empNo);

            // Read employee Data to display
            data.ReadEmployee(empNo);

            // To print strings on the text field showData
            ByteArrayOutputStream output = new ByteArrayOutputStream();
            PrintStream ps = new PrintStream(output);
            PrintStream old = System.out;
            System.setOut(ps);
            System.out.flush();
            System.setOut(old);

            // Catch an invalid input of employee number
            if (data.EmployeeNo() == null) {
                infoText.append("\n\t*** Employee Not Found! ***").append("\n");
            } else {
                // Construct the salary information
                infoText.append("Employee No.: ").append(data.EmployeeNo()).append("\n\n");
                infoText.append("Employee Name: ").append(data.EmployeeFN()).append(" ").append(data.EmployeeLN()).append("\n\n");
                infoText.append("Date of Birth: ").append(data.EmployeeDOB()).append("\n\n");
                infoText.append("Address: ").append(data.EmployeeAddress()).append("\n\n");
                infoText.append("Phone #: ").append(data.EmployeePhoneNumber()).append("\n\n");
                infoText.append("SSS #: ").append(data.EmployeeSSS()).append("\n\n");
                infoText.append("PhilHealth #: ").append(data.EmployeePhilHealth()).append("\n\n");
                infoText.append("TIN: ").append(data.EmployeeTIN()).append("\n\n");
                infoText.append("Pag-Ibig #: ").append(data.EmployeePagIbig()).append("\n\n");
                infoText.append("Employment Status: ").append(data.EmployeeStatus()).append("\n\n");
                infoText.append("Company Position: ").append(data.EmployeePosition()).append("\n\n");
                infoText.append("Immediate Supervisor: ").append(data.EmployeeSupervisor()).append("\n\n"); 
            }
            showData.setText(infoText.toString());
        } catch (CsvValidationException | IOException  ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_viewEmpDataActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewSalary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewSalary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewSalary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewSalary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewSalary().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel date;
    private javax.swing.JTextField employeeNo;
    private javax.swing.JTextField hw;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private javax.swing.JTextArea showData;
    private javax.swing.JButton viewButton;
    private javax.swing.JButton viewEmpData;
    // End of variables declaration//GEN-END:variables
}
